name: mdes-stub
version: 0.1.3

ghc-options: -Wall -fno-warn-unused-do-bind

dependencies: base

executables:
  mdes-stub:
    main: Main.hs
    ghc-options: -threaded -O2 -rtsopts -with-rtsopts=-N
    dependencies: [mdes-stub, docopt]

library:
  source-dirs: src
  exposed-modules: Server.MDES
  dependencies:
    - aeson
    - containers
    - aeson
    - containers
    - file-embed
    - text
    - base64-bytestring
    - lens
    - cryptonite
    - attoparsec
    - mtl
    - x509
    - x509-store
    - data-default-class
    - scotty
    - warp
    - http-types
    - wai
    - wai-extra
    - transformers
    - bytestring
    - base16-bytestring
    - time
    - wreq
    - random
    - hslogger
